load mex headers from s3 metadata
NHSDigital/spine-core-aws-common pull request #86
Opened 2023-05-29 20:28 UTC by jens-kursch-NHSD

2023-05-29 21:46 UTC, jens-kursch-NHSD commented
I'm not sure how to write a test to confirm that the headers are used in the request to mesh. Suggestions are appreciated.

2023-05-30 14:14 UTC, jens-kursch-NHSD commented
Pull request has been updated with test

2023-06-01 12:05 UTC, ranisen reviewed
This looks ok - one question is what happens if the metadata is mixed case? Does this handle this correctly if the S3 metadata is:
`"MeX-sUbJeCt": "Custom Subject"`
As headers names (as part of the HTTP spec) are supposed to be case insensitive?

2023-06-01 15:05 UTC, jens-kursch-NHSD commented
This is a limitation of using s3 metadata. The key in the s3 metadata is forced to be lowercase.

2023-06-02 12:24 UTC, ranisen requested changes

2023-06-02 12:24 UTC, ranisen commented on mesh_aws_client/mesh_mailbox.py
> +        for key, value in mesh_message_object.metadata.items():
This will break if metadata is None.
You should really set metadata to an empty dict {}

2023-06-02 12:24 UTC, ranisen commented on mesh_aws_client/mesh_mailbox.py
> +        for key, value in mesh_message_object.metadata.items():
Or check if it's None before trying to iterate it

2023-06-07 08:59 UTC, jens-kursch-NHSD commented on mesh_aws_client/mesh_mailbox.py
> +        for key, value in mesh_message_object.metadata.items():
I've refactored it out into a function that checks for None and Empty dict

2023-06-09 14:07 UTC, ranisen approved these changes

2023-06-09 14:07 UTC, merged