Fix S3 acl issue
NHSDigital/spine-core-aws-common pull request #88
Opened 2023-09-06 11:18 UTC by TeiturArgeSeloy

# Changes
- Update aws version to 1.10.0.
- Use Boolean value for count  aws_ssm_parameter.

# Note!
This PR is an amendment of https://github.com/NHSDigital/spine-core-aws-common-3/pull/1
The Notify a Patient service is currently using [bugfix/s3_acl_issue](https://github.com/NHSDigital/spine-core-aws-common-3/tree/bugfix/s3_acl_issue) version in production

# Test
This PR has been tested on the Notify a Patient service with the following tests:
- send message
- Pull message from mailbox

2023-09-06 11:44 UTC, matt-mercer approved these changes

2023-09-06 11:47 UTC, matt-mercer requested changes

2023-09-06 11:47 UTC, matt-mercer commented on terraform/mesh_aws/s3_logs.tf
> -  acl    = "log-delivery-write"
is this a problem that we're removing the log delivery-write  ACL here ?  should we be adding a aws_s3_bucket_acl resource as well ?

2023-09-07 14:35 UTC, TeiturArgeSeloy commented on terraform/mesh_aws/s3_logs.tf
> -  acl    = "log-delivery-write"
Added aws_s3_bucket_server_side_encryption_configuration and aws_s3_bucket_acl for the acl and  server_side_encryption_configuration

2023-09-07 14:56 UTC, matt-mercer approved these changes

2023-09-08 12:50 UTC, merged